---
- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: cis_baseline_apply_runtime

- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  when: cis_baseline_apply_runtime

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: cis_baseline_apply_runtime

- name: Reload sysctl
  ansible.builtin.command: sysctl --system  # noqa: command-instead-of-module
  when: cis_baseline_apply_runtime
  changed_when: false
